version: 0.0.{build}
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2019
configuration: Release
before_build:
  - nuget restore
build:
  project: SitecoreUpgradeAssist.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: Src\TargetFrameworkMigratorVSIX\**\*.vsix